coffee/urls.py
from django.urls import re_path
from . import views


app_name = 'coffee'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'brews.json$', views.brew_list_page, name='brew-list-json'),
    re_path(r'^search/?$', views.search, name='search'),
    re_path(r'^bags/?$', views.all_bags, name='all-bags'),
    re_path(r'^brew/(\d+)/?$', views.brew_details, name='brew-details'),
    re_path(r'^brew/(\d+)/edit/?$', views.edit_brew, name='brew-edit'),
    re_path(r'^brew/(\d+)/copy/?$', views.copy_brew, name='brew-copy'),
    re_path(r'^brew/(\d+)/rate/?$', views.rate_brew, name='brew-rate'),
    re_path(r'^brew/add/?$', views.create_brew, name='brew-create'),
    re_path(r'^bags/(\d+)/?$', views.coffee_bag, name='bag-details'),
    re_path(r'^bags/(\d+)/add/?$', views.create_brew_for_bag, name='brew-create-for-bag'),
    re_path(r'^bags/(\d+)/edit/?$', views.edit_coffee_bag, name='bag-edit'),
    re_path(r'^bags/(\d+)/copy/?$', views.copy_coffee_bag, name='bag-copy'),
    re_path(r'^coffee/(\d+)/?$', views.coffee_details, name='coffee-details'),
    re_path(r'^roasters/?$', views.roaster_list, name='roasters'),
    re_path(r'^roasters/(\d+)/?$', views.roaster, name='roaster-details'),
    re_path(r'^methods/?$', views.method_list, name='methods'),
    re_path(r'^methods/(\d+)/?$', views.method_details, name='brewing-method'),
    re_path(r'^water/?$', views.water_list, name='waters'),
    re_path(r'^water/(\d+)/?$', views.water_details, name='water'),
    re_path(r'^notes/?$', views.descriptor_list, name='notes'),
    re_path(r'^notes/(\d+)/?$', views.descriptor, name='note-details'),
    re_path(r'^rating/(\d+)/?$', views.brews_by_rating_value, name='brews-by-rating-value'),
    re_path(r'^stats/?$', views.stats, name='stats'),
]

coffee/models.py
import os
import datetime
from io import BytesIO
from PIL import Image
from django.db import models
from django.urls import reverse
from django.core.files.base import ContentFile
from .utils import get_time_display


class City(models.Model):
    name = models.CharField(max_length=512)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'


class Roaster(models.Model):
    name = models.CharField(max_length=512)
    city = models.ForeignKey(City, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('coffee:roaster-details', args=[self.id])


class RoastProfile(models.Model):
    name = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class Grinder(models.Model):
    SIMPLE = 0
    AERGRIND = 1

    name = models.CharField(max_length=512)
    comment = models.TextField(null=True, blank=True)
    default = models.BooleanField(default=False)
    adjust_type = models.IntegerField(choices=(
        (SIMPLE, "Simple"),
        (AERGRIND, "Aergrind"),
    ), default=SIMPLE)

    def get_setting_display(self, value):
        if self.adjust_type == self.AERGRIND:
            return '%d,%d' % (value / 12, value % 12)

        return str(value)

    def __str__(self):
        return self.name


class Coffee(models.Model):
    WASHED = 1
    DRY = 2
    HONEY = 3

    name = models.CharField(max_length=512)
    short_name = models.CharField(max_length=32, blank=True, null=True)
    processing = models.IntegerField(choices=(
        (WASHED, "Washed"),
        (DRY, "Dry"),
        (HONEY, "Honey"),
    ), blank=True, null=True)
    roaster = models.ForeignKey(Roaster, on_delete=models.CASCADE)
    roast_profile = models.ForeignKey(RoastProfile, blank=True, null=True, on_delete=models.CASCADE)
    roaster_comment = models.TextField(null=True, blank=True)
    descriptors = models.ManyToManyField('Descriptor', blank=True)

    def get_absolute_url(self):
        return reverse('coffee:coffee-details', args=[self.id])

    def __str__(self):
        result = self.name
        if self.roast_profile:
            result += ' ' + self.roast_profile.name
        return result

    def get_short_name(self):
        if self.short_name:
            return self.short_name
        return self.name


class CoffeeBag(models.Model):
    NOT_FINISHED = 0
    FINISHED = 1
    THROWN_AWAY = 2
    GIVEN_AWAY = 3
    LOST = 4

    coffee = models.ForeignKey(Coffee, on_delete=models.CASCADE)
    weight = models.IntegerField(blank=True, null=True)
    roast_date = models.DateField(blank=True, null=True)
    purchase_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    status = models.IntegerField(choices=(
        (NOT_FINISHED, 'Not finished'),
        (FINISHED, 'Finished'),
        (THROWN_AWAY, 'Thrown away'),
        (GIVEN_AWAY, 'Given away'),
        (LOST, 'Lost'),
    ), default=NOT_FINISHED)
    roaster_comment = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='bags/full/', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='bags/thumbs/', blank=True, null=True)

    _original_image = None

    def __init__(self, *args, **kwargs):
        super(CoffeeBag, self).__init__(*args, **kwargs)
        self._original_image = self.image

    def __str__(self):
        name = '{} ({})'.format(self.coffee, self.coffee.roaster.name)
        if self.roast_date is not None:
            name += ' ' + self.roast_date.strftime('%Y-%m-%d')
        return name

    def get_absolute_url(self):
        return reverse('coffee:bag-details', args=[self.id])

    def get_weight_display(self):
        if self.weight is None:
            return ''
        return '{}g'.format(self.weight)

    def get_date_only_name(self):
        if self.roast_date is None:
            return 'Purchased on ' + self.purchase_date.strftime('%Y-%m-%d')
        else:
            return 'Roasted on ' + self.roast_date.strftime('%Y-%m-%d')

    def save(self, *args, **kwargs):
        if self.image:
            image_changed = False
            if self._original_image:
                if self._original_image.size != self.image.size:
                    image_changed = True
                else:
                    data1 = self._original_image.file.read()
                    self.image.file.seek(0)
                    data2 = self.image.file.read()
                    self._original_image.file.seek(0)
                    if data1 != data2:
                        image_changed = True
            else:
                image_changed = True

            if image_changed:
                thumb_size = (130, 170)
                image = Image.open(BytesIO(self.image.read()))
                image.thumbnail(thumb_size, Image.ANTIALIAS)

                thumb_stream = BytesIO()
                image.save(thumb_stream, 'jpeg', quality=95)

                thumb_stream.seek(0)

                uploaded_file = ContentFile(thumb_stream.read())

                self.thumbnail.save(
                    os.path.basename(self.image.name),
                    uploaded_file,
                    save=False,
                )
        else:
            self.thumbnail = None
        super(CoffeeBag, self).save(*args, **kwargs)


class BagPicture(models.Model):
    bag = models.ForeignKey(CoffeeBag, related_name='extra_pictures', on_delete=models.CASCADE)
    comment = models.CharField(max_length=512, blank=True, null=True)
    image = models.ImageField(upload_to='bags/full/')
    thumbnail = models.ImageField(upload_to='bags/thumbs/', blank=True, null=True)

    def __str__(self):
        name = str(self.bag)
        if self.comment:
            name += ' ' + self.comment
        return name

    def save(self, *args, **kwargs):
        thumb_size = (100, 100)
        image = Image.open(BytesIO(self.image.read()))
        image.thumbnail(thumb_size, Image.ANTIALIAS)

        thumb_stream = BytesIO()
        image.save(thumb_stream, 'jpeg', quality=95)

        thumb_stream.seek(0)

        uploaded_file = ContentFile(thumb_stream.read())

        self.thumbnail.save(
            os.path.basename(self.image.name),
            uploaded_file,
            save=False,
        )
        super(BagPicture, self).save(*args, **kwargs)


class Water(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('coffee:water', args=[self.id])


class BrewingMethod(models.Model):
    name = models.CharField(max_length=512)
    default_filter = models.ForeignKey('Filter', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('coffee:brewing-method', args=[self.id])


class Filter(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=256)
    default_barista = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class BrewQuerySet(models.QuerySet):

    _aggregation_data_loaded = False
    max_rating = None
    total_weight = None
    def _calc_aggregation_data(self):
        max_rating = None
        total_weight = 0

        for brew in self:
            if brew.coffee_weight is not None:
                total_weight += brew.coffee_weight
            if brew.rating is not None and (max_rating is None or brew.rating > max_rating):
                max_rating = brew.rating

        self._aggregation_data_loaded = True
        self.max_rating = max_rating
        self.total_weight = total_weight

    def get_total_weight(self):
        if not self._aggregation_data_loaded:
            self._calc_aggregation_data()

        return self.total_weight

    def get_max_rating(self):
        if not self._aggregation_data_loaded:
            self._calc_aggregation_data()

        return self.max_rating


class Brew(models.Model):
    BLOOM_UNKNOWN = 0
    BLOOM = 1
    NO_BLOOM = 2
    RATING_MAX = 10

    UNDER_EXTRACTED = -1
    BALANCED = 0
    OVER_EXTRACTED = 1
    extraction_symbols = {
        UNDER_EXTRACTED: '&darr;',
        BALANCED: '&check;',
        OVER_EXTRACTED: '&uarr;',
    }

    objects = BrewQuerySet.as_manager()

    datetime = models.DateTimeField()
    coffee_bag = models.ForeignKey(CoffeeBag, on_delete=models.CASCADE)
    barista = models.ForeignKey(Person, blank=True, null=True, on_delete=models.CASCADE)
    grinder = models.ForeignKey(Grinder, blank=True, null=True, on_delete=models.CASCADE)
    grinder_setting = models.IntegerField()
    method = models.ForeignKey(BrewingMethod, on_delete=models.CASCADE)
    temperature = models.IntegerField(blank=True, null=True)
    coffee_weight = models.IntegerField(blank=True, null=True)
    water_volume = models.IntegerField(blank=True, null=True)
    result_volume = models.IntegerField(blank=True, null=True)
    water = models.ForeignKey(Water, blank=True, null=True, on_delete=models.CASCADE)
    water_tds = models.IntegerField(blank=True, null=True)
    brew_time = models.IntegerField(blank=True, null=True)
    bloom = models.SmallIntegerField(choices=(
        (BLOOM_UNKNOWN, 'Unknown'),
        (BLOOM, 'Bloom'),
        (NO_BLOOM, 'No bloom'),
    ), default=0)
    filter = models.ForeignKey(Filter, blank=True, null=True, on_delete=models.CASCADE)
    found_descriptors = models.ManyToManyField('Descriptor', blank=True)
    extraction = models.SmallIntegerField(blank=True, null=True, choices=(
        (UNDER_EXTRACTED, 'Недоэкстрагирован'),
        (BALANCED, 'Сбалансирован'),
        (OVER_EXTRACTED, 'Переэкстрагирован'),
    ))
    rating = models.SmallIntegerField(blank=True, null=True, choices=((i, i) for i in range(1, 11)))

coffee/forms.py
from django.db.models import Q
from django import forms
from .models import CoffeeBag, Brew, Descriptor
from .utils import get_time_display
from .widgets import MultiSelectCheckboxWidget


class DurationWidget(forms.TextInput):
    def format_value(self, value):
        if isinstance(value, str):
            return value
        if value:
            return get_time_display(value)
        return ''


class DurationField(forms.CharField):
    def to_python(self, value):
        if not value:
            return None

        if ':' not in value:
            raise forms.ValidationError('Incorrect format for duration')

        split = value.split(':', 2)

        hours = 0
        if len(split) == 3:
            if not split[0].isdigit():
                raise forms.ValidationError('Incorrect hours value')
            hours = int(split[0])
            minutes_str = split[1]
            seconds_str = split[2]
        elif len(split) == 2:
            minutes_str = split[0]
            seconds_str = split[1]
        else:
            raise forms.ValidationError('Incorrect duration format')

        if not minutes_str.isdigit():
            raise forms.ValidationError('Incorrect minutes value')

        minutes = int(minutes_str)

        if hours > 0 and minutes > 59:
            raise forms.ValidationError('Minutes value out of range')

        if not seconds_str.isdigit():
            raise forms.ValidationError('Incorrect seconds value')

        seconds = int(seconds_str)

        if seconds > 59:
            raise forms.ValidationError('Seconds value out of range')

        return hours * 3600 + minutes * 60 + seconds


class BrewForm(forms.ModelForm):
    coffee_bag = forms.ModelChoiceField(queryset=CoffeeBag.objects.filter(status=CoffeeBag.NOT_FINISHED))
    brew_time = DurationField(widget=DurationWidget, required=False)

    def __init__(self, *args, **kwargs):
        super(BrewForm, self).__init__(*args, **kwargs)
        if self.instance.pk is not None:
            self.fields['coffee_bag'].queryset = CoffeeBag.objects.filter(
                Q(end_date__isnull=True)|Q(id=self.instance.coffee_bag_id)
            )

    class Meta:
        model = Brew
        exclude = ['id']
        labels = {
            'water_tds': 'TDS',
        }
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4, 'cols': 35}),
            'extraction': forms.RadioSelect(),
            'found_descriptors': MultiSelectCheckboxWidget(),
        }


class BrewRatingForm(forms.ModelForm):
    class Meta:
        model = Brew
        fields = ['rating']


class CoffeeBagForm(forms.ModelForm):
    class Meta:
        model = CoffeeBag
        exclude = ['id', 'thumbnail']
        widgets = {
            'roaster_comment': forms.TextInput(),
        }

coffee/templates/coffee/all_coffee.html
{% extends "coffee/bag_list_page.html" %}
{% block heading %}Весь кофе{% endblock %}

coffee/templates/coffee/bag_list_page.html
{% extends "coffee/base.html" %}
{% block content %}
<ul class="breadcrumbs">
    <li><a href="{% url 'coffee:index' %}">Главная</a></li><li>&rarr;</li>
    <li><a href="{% url 'coffee:all-bags' %}">Кофе</a></li>
    {% block breadcrumbs %}{% endblock %}
</ul>
<h2>{% block heading %}{% endblock %}</h2>
{% include "coffee/bag_list.html" %}
{% endblock %}

coffee/templates/coffee/coffee_bag.html
{% extends "coffee/base.html" %}
{% load static %}
{% block content %}
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<ul class="breadcrumbs">
    <li><a href="{% url 'coffee:index' %}">Главная</a></li><li>&rarr;</li>
    <li><a href="{% url 'coffee:all-bags' %}">Кофе</a></li><li>&rarr;</li>
    <li><a href="{{ bag.get_absolute_url }}">{{ bag.coffee.get_short_name }}</a></li>
</ul>
<div class="bag-details-subheader">
    <div class="bag-thumb" id="bag-thumb">
    {% if bag.thumbnail %}
        <a href="{{ bag.image.url }}" data-gallery><img src="{{ bag.thumbnail.url }}"></a>
    {% else %}
        <a><img src="{% static "images/generic-bag-small.png" %}"></a>
    {% endif %}
    </div>
    <div class="bag-name-block">
        <h3>{{ bag.coffee.name }}</h3>
        <ul class="bag-details">
            <li><span class="param-name">Обжарщик:</span> <a href="{{ bag.coffee.roaster.get_absolute_url }}">{{ bag.coffee.roaster }}</a></li>
            <li><span class="param-name">Обжарка:</span> {% if bag.coffee.roast_profile %}{{ bag.coffee.roast_profile }}{% else %}-{% endif %}</li>
            <li><span class="param-name">Вес:</span> {{ bag.get_weight_display }}</li>
            <li><span class="param-name">Дата обжарки:</span> {% if bag.roast_date %}{{ bag.roast_date }}{% else %}-{% endif %}</li>
            <li><span class="param-name">Дата приобретения:</span> {{ bag.purchase_date }}</li>
            {% if bag.end_date %}
            <li><span class="param-name">Дата окончания:</span> {{ bag.end_date }}</li>
            {% endif %}
            {% if bag.coffee.roaster_comment %}
            <li><span class="param-name">Комментарий обжарщика:</span> {{ bag.coffee.roaster_comment }}</li>
            {% endif %}
            {% if all_descriptors %}
            <li><span class="param-name">Дескрипторы:</span>
                {% for descriptor in all_descriptors %}
                <a href="{{ descriptor.get_absolute_url }}">{{ descriptor }}</a>{% if not forloop.last %},{% endif %}
                {% endfor %}
            </li>
            {% endif %}
            {% if bag_descriptors %}
            <li><span class="param-name">В этой пачке:</span>
                {% for descriptor in bag_descriptors %}
                <a href="{{ descriptor.get_absolute_url }}">{{ descriptor }}</a>{% if not forloop.last %},{% endif %}
                {% endfor %}
            </li>
            {% endif %}
        </ul>
    </div>
</div>

{% if bag.extra_pictures.count %}
<div class="bag-extra-pictures">
    {% for pic in bag.extra_pictures.all %}
    <div class="bag-thumb">
        <a href="{{ pic.image.url }}" data-gallery><img src="{{ pic.thumbnail.url }}"></a>
    </div>
    {% endfor %}
</div>
{% endif %}


{% if request.user.is_authenticated %}
<p>
    <a href="{% url 'coffee:brew-create-for-bag' bag.id %}">Add brew</a> |
    <a href="{% url 'coffee:bag-edit' bag.id %}">Edit</a> |
    <a href="{% url 'coffee:bag-copy' bag.id %}">Copy</a>
</p>
{% endif %}
        <script type="text/javascript" src="{% static "js/blueimp-gallery.js" %}"></script>
        <script type="text/javascript" src="{% static "js/jquery.blueimp-gallery.js" %}"></script>
{% endblock %}

{% block brew_list %}
{% include "coffee/brew_list.html" %}
{% endblock %}

{% block after_brew_list_content %}
<div class="content-wrapper">
    {% if other_bags %}
    <h4>Другие пачки кофе {{ bag.coffee.name }}</h4>
        {% include "coffee/bag_list.html" with bags=other_bags %}
    {% endif %}
</div>
{% endblock %}
{% block extra_css %}
        <link rel="stylesheet" href="{% static "css/blueimp-gallery.css" %}">
{% endblock %}

coffee/templates/coffee/descriptor.html
{% extends "coffee/base.html" %}
{% block content %}
<h3>{{ descriptor.name }}</h3>
{% endblock %}
{% block brew_list %}
{% include "coffee/brew_list.html" %}
{% endblock %}

coffee/templates/coffee/descriptor_list.html
{% extends "coffee/base.html" %}
{% block content %}
<ul class="breadcrumbs">
    <li><a href="{% url 'coffee:index' %}">Главная</a></li><li>&rarr;</li>
    <li><a href="{% url 'coffee:notes' %}">Ноты</a></li>
</ul>
<h2>Ноты (дескрипторы)</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Название</th>
            <th>Сколько раз найден</th>
        </tr>
    </thead>
    <tbody>
        {% for descriptor in descriptors %}
        <tr>
            <td><a href="{{ descriptor.get_absolute_url }}">{{ descriptor.name }}</a></td>
            <td>{{ descriptor.count }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

coffee/templates/coffee/index.html
{% extends "coffee/base.html" %}
{% load static %}
{% block content %}
<ul class="coffee-bags index-list">
    {% for bag in bags %}
    <li>
        <div class="bag-image">
        <a href="{{ bag.get_absolute_url }}">
            {% if bag.thumbnail %}
            <img src="{{ bag.thumbnail.url }}">
            {% else %}
            <img src="{% static "images/generic-bag-small.png" %}">
            {% endif %}
        </a>
        </div>
        <div class="bag-name"><a href="{{ bag.get_absolute_url }}">{% if bag.coffee.short_name %}{{ bag.coffee.short_name }}{% else %}{{ bag.coffee.name }}{% endif %}</a></div>
        <div class="bag-weight">{{ bag.get_weight_display }}</div>
        <div class="bag-roaster"><a href="{{ bag.coffee.roaster.get_absolute_url }}">{{ bag.coffee.roaster.name }}</a></div>
    </li>
    {% endfor %}
</ul>
<div class="show-more-coffee">Развернуть</div>

{% if request.user.is_authenticated %}
<p>
<a href="{% url 'coffee:brew-create' %}">Add brew</a>
</p>
{% endif %}
<script>
$(function() {
    var expanded = false;
    $(".show-more-coffee").click(function() {
        if (expanded) {
            $(".coffee-bags").animate({
                height: 240
            },
            {
                complete: function() {
                    expanded = false;
                    $(".show-more-coffee").text("Развернуть");
                }
            });
        }
        else {
            var full_height = $(".coffee-bags")[0].scrollHeight;
            $(".coffee-bags").animate({
                height: full_height
            },
            {
                complete: function() {
                    expanded = true;
                    $(".show-more-coffee").text("Свернуть");
                }
            });
        }
    });
});
</script>
{% endblock %}
{% block brew_list %}
{% include "coffee/brew_list.html" %}
{% endblock %}

coffee/templates/coffee/method_list.html
{% extends "coffee/base.html" %}
{% block content %}
<ul class="breadcrumbs">
    <li><a href="{% url 'coffee:index' %}">Главная</a></li><li>&rarr;</li>
    <li><a href="{% url 'coffee:methods' %}">Способы заваривания</a></li>
</ul>
<h2>Способы заваривания кофе</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Способ</th>
            <th>Чашек заварено</th>
            <th>Средний рейтинг</th>
        </tr>
    </thead>
    <tbody>
        {% for method in methods %}
        <tr>
            <td><a href="{{ method.get_absolute_url }}">{{ method.name }}</a></td>
            <td>{{ method.count }}</td>
            <td>{{ method.avg_rating|floatformat:1 }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

coffee/templates/coffee/roaster_list.html
{% extends "coffee/base.html" %}
{% block content %}
<ul class="breadcrumbs">
    <li><a href="{% url 'coffee:index' %}">Главная</a></li><li>&rarr;</li>
    <li><a href="{% url 'coffee:roasters' %}">Обжарщики</a></li>
</ul>
<h2>Обжарщики</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Обжарщик</th>
            <th>Город</th>
            <th>Чашек заварено</th>
            <th>Кофе израсходовано, кг</th>
            <th>Средний рейтинг</th>
            <th>Средний рейтинг за последние 100 чашек</th>
        </tr>
    </thead>
    <tbody>
        {% for roaster in roasters %}
        <tr>
            <td><a href="{{ roaster.get_absolute_url }}">{{ roaster.name }}</a></td>
            <td>{% if roaster.city %}{{ roaster.city }}{% endif %}</td>
            <td>{{ roaster.count }}</td>
            <td>{% if roaster.coffee_consumed %}{{ roaster.coffee_consumed|floatformat:3 }}{% else %}0{% endif %}</td>
            <td>{{ roaster.avg_rating|floatformat:1 }}</td>
            <td>{% if roaster.recent_rating %}{{ roaster.recent_rating|floatformat:1 }}{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

coffee/templates/coffee/stats.html
{% extends "coffee/base.html" %}
{% block content %}
<ul class="breadcrumbs">
    <li><a href="{% url 'coffee:index' %}">Главная</a></li><li>&rarr;</li>
    <li><a href="{% url 'coffee:roasters' %}">Статистика</a></li>
</ul>
<h1>Статистика</h1>
<table class="table">
    <thead>
        <tr>
            <td></td>
            <th>За всё время</th>
            <th>За последние 100 чашек</th>
            <th>За последние 7 дней</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Всего заварено чашек</td>
            <td>{{ total_stats.brews }}</td>
            <td>{{ last100_stats.brews }}</td>
            <td>{{ last_week_stats.brews }}</td>
        </tr>
        <tr>
            <td>Всего потрачено кофе</td>
            <td>{{ total_stats.consumed_coffee_weight|floatformat:3 }}кг</td>
            <td>{{ last100_stats.consumed_coffee_weight|floatformat:3 }}кг</td>
            <td>{{ last_week_stats.consumed_coffee_weight|floatformat:3 }}кг</td>
        </tr>
        <tr>
            <td>Осталось свежего кофе</td><td colspan="3">{{ unexpired_coffee_weight }}г
                {% if unexpired_coffee_weight > 0 %}(
                хватит на {{ days_left }} д
                ){% endif %}
            </td>
        </tr>
        <tr>
            <td>Средний рейтинг</td>
            <td>{{ total_stats.avg_rating|floatformat:1 }}</td>
            <td>{{ last100_stats.avg_rating|floatformat:1 }}</td>
            <td>{{ last_week_stats.avg_rating|floatformat:1 }}</td>
        </tr>
        <tr>
            <td>Воды потрачено для заваривания кофе</td>
            <td>{{ total_stats.consumed_water|floatformat:3 }} л</td>
            <td>{{ last100_stats.consumed_water|floatformat:3 }} л</td>
            <td>{{ last_week_stats.consumed_water|floatformat:1 }} л</td>
        </tr>
        <tr>
            <td>Средняя скорость потребления кофе</td>
            <td>{{ total_stats.consumption_rate|floatformat:1 }} г/день</td>
            <td>{{ last100_stats.consumption_rate|floatformat:1 }} г/день</td>
            <td>{{ last_week_stats.consumption_rate|floatformat:1 }} г/день</td>
        </tr>
        {% for rating, brew_count_total, brew_count_last100, brew_count_last_week in brews_by_rating %}
        <tr>
            <td>Оценок {{ rating }}/10</td>
            <td>{% if brew_count_total > 0 %}<a href="{% url 'coffee:brews-by-rating-value' rating %}">{{ brew_count_total }}</a>{% else %}0{% endif %}</td>
            <td>{% if brew_count_last100 > 0 %}<a href="{% url 'coffee:brews-by-rating-value' rating %}">{{ brew_count_last100 }}</a>{% else %}0{% endif %}</td>
            <td>{% if brew_count_last_week > 0 %}<a href="{% url 'coffee:brews-by-rating-value' rating %}">{{ brew_count_last_week }}</a>{% else %}0{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

coffee/templates/coffee/water_list.html
{% extends "coffee/base.html" %}
{% block content %}
<ul class="breadcrumbs">
    <li><a href="{% url 'coffee:index' %}">Главная</a></li><li>&rarr;</li>
    <li><a href="{% url 'coffee:waters' %}">Вода</a></li>
</ul>
<h2>Вода</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Марка воды</th>
            <th>Чашек заварено</th>
            <th>Средний рейтинг за всё время</th>
            <th>Средний рейтинг за последние 100 чашек</th>
        </tr>
    </thead>
    <tbody>
        {% for water in waters %}
        <tr>
            <td><a href="{{ water.get_absolute_url }}">{{ water.name }}</a></td>
            <td>{{ water.count }}</td>
            <td>{{ water.avg_rating|floatformat:1 }}</td>
            <td>{% if water.recent_rating %}{{ water.recent_rating|floatformat:1 }}{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}